//! Signal value types for IRIS simulator
//!
//! The types live in `iris-runtime` so that the interpreter and the code
//! generated by `iris-compile` operate on the same values.

pub use iris_runtime::value::{BitValue, SignalValue};
