//! Value-level operations
//!
//! Every arithmetic, comparison and bit-selection rule of the language lives
//! here. The interpreter calls these functions while walking the syntax tree,
//! and the code generated by `iris-compile` calls the same functions with the
//! operands already resolved. A design therefore cannot mean one thing when
//! interpreted and another when compiled.

use crate::value::{FloatFmt, SignalValue};

/// Binary operators
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BinOp {
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    And,
    Or,
    Xor,
    Shl,
    Shr,
    /// Arithmetic (sign-replicating) right shift
    AShr,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    LogicalAnd,
    LogicalOr,
}

/// Unary operators
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnaryOp {
    /// Bitwise complement
    Not,
    /// Two's complement negation
    Neg,
    /// Logical negation, yielding one bit
    LogNot,
}

impl BinOp {
    /// Does this operator yield a single bit regardless of its operands?
    pub fn is_relational(self) -> bool {
        matches!(
            self,
            BinOp::Eq
                | BinOp::Ne
                | BinOp::Lt
                | BinOp::Le
                | BinOp::Gt
                | BinOp::Ge
                | BinOp::LogicalAnd
                | BinOp::LogicalOr
        )
    }

    /// Does the result depend on how the operand bits are read?
    ///
    /// A shift takes its signedness from the value being shifted alone: the
    /// shift amount is a magnitude.
    fn signedness_from_lhs_only(self) -> bool {
        matches!(self, BinOp::Shl | BinOp::Shr | BinOp::AShr)
    }
}

/// Is this value non-zero? Unknown bits read as false.
#[inline]
pub fn truthy(value: &SignalValue) -> bool {
    value.to_u64().map(|v| v != 0).unwrap_or(false)
}

/// Width of a binary operation's result.
///
/// An unsized decimal literal takes the width of the other operand, so that
/// `ptr + 1` wraps at the width of `ptr` instead of at 32 bits.
pub fn binop_width(
    op: BinOp,
    lhs: &SignalValue,
    rhs: &SignalValue,
    lhs_unsized: bool,
    rhs_unsized: bool,
) -> usize {
    if op.is_relational() {
        return 1;
    }
    match (lhs_unsized, rhs_unsized) {
        (false, true) => lhs.width(),
        (true, false) => rhs.width(),
        _ => lhs.width().max(rhs.width()),
    }
}

/// Is this operation performed on two's complement operands?
pub fn binop_is_signed(op: BinOp, lhs: &SignalValue, rhs: &SignalValue) -> bool {
    if op.signedness_from_lhs_only() {
        lhs.is_signed()
    } else {
        lhs.is_signed() && rhs.is_signed()
    }
}

/// An operation whose result depends on the operands being signed.
///
/// Returns `None` for the operations that give the same bits either way:
/// addition, subtraction, multiplication and the bitwise operators.
fn signed_binop(
    op: BinOp,
    lhs: &SignalValue,
    rhs: &SignalValue,
    width: usize,
) -> Option<SignalValue> {
    let (lv, rv) = (lhs.to_i64()?, rhs.to_i64()?);
    let one = |b: bool| SignalValue::from_u64(b as u64, 1);
    match op {
        // Equality on signed operands compares by value, so a narrow signed
        // value equals a wider one of the same value (e.g. `int[8] -7 == -7`,
        // where the literal is a 32-bit signed value). Same-width operands are
        // unaffected: unsigned-equal and signed-equal coincide there.
        BinOp::Eq => Some(one(lv == rv)),
        BinOp::Ne => Some(one(lv != rv)),
        BinOp::Lt => Some(one(lv < rv)),
        BinOp::Le => Some(one(lv <= rv)),
        BinOp::Gt => Some(one(lv > rv)),
        BinOp::Ge => Some(one(lv >= rv)),
        BinOp::Div if rv != 0 => Some(SignalValue::from_i64(lv / rv, width)),
        BinOp::Mod if rv != 0 => Some(SignalValue::from_i64(lv % rv, width)),
        BinOp::AShr => Some(SignalValue::from_i64(lv >> (rv as u32).min(63), width)),
        _ => None,
    }
}

/// Apply a binary operator.
///
/// `lhs_unsized` and `rhs_unsized` say whether the operand was written as a
/// decimal literal without a width suffix; they only affect the result width.
#[inline]
pub fn binop(
    op: BinOp,
    lhs: &SignalValue,
    rhs: &SignalValue,
    lhs_unsized: bool,
    rhs_unsized: bool,
) -> SignalValue {
    let width = binop_width(op, lhs, rhs, lhs_unsized, rhs_unsized);
    let signed = binop_is_signed(op, lhs, rhs);

    if signed {
        if let Some(result) = signed_binop(op, lhs, rhs, width) {
            return result;
        }
    }

    let lv = lhs.to_u64().unwrap_or(0);
    let rv = rhs.to_u64().unwrap_or(0);
    let result = match op {
        BinOp::Add => lv.wrapping_add(rv),
        BinOp::Sub => lv.wrapping_sub(rv),
        BinOp::Mul => lv.wrapping_mul(rv),
        BinOp::Div => {
            if rv != 0 {
                lv / rv
            } else {
                0
            }
        }
        BinOp::Mod => {
            if rv != 0 {
                lv % rv
            } else {
                0
            }
        }
        BinOp::And => lv & rv,
        BinOp::Or => lv | rv,
        BinOp::Xor => lv ^ rv,
        BinOp::Shl => lv << (rv as u32),
        BinOp::Shr => lv >> (rv as u32),
        // Without signed operands an arithmetic shift is a logical one
        BinOp::AShr => lv >> (rv as u32),
        BinOp::Eq => (lv == rv) as u64,
        BinOp::Ne => (lv != rv) as u64,
        BinOp::Lt => (lv < rv) as u64,
        BinOp::Le => (lv <= rv) as u64,
        BinOp::Gt => (lv > rv) as u64,
        BinOp::Ge => (lv >= rv) as u64,
        BinOp::LogicalAnd => (lv != 0 && rv != 0) as u64,
        BinOp::LogicalOr => (lv != 0 || rv != 0) as u64,
    };

    SignalValue::from_u64(result, width).with_signed(signed)
}

/// A floating-point binary operation, shared by the interpreter and the code
/// `iris-compile` generates so the two agree.
///
/// The operands' bits are read as `fmt`, the operation runs in that precision
/// (so rounding is the format's own), and an arithmetic result is encoded back
/// to the same format. A comparison yields one bit. An operator that floating
/// point does not define (a bitwise or shift operator) falls back to the
/// integer operation on the raw bits, matching how such an operator would be
/// applied to the stored pattern. Unknown bits yield an unknown value.
pub fn float_binop(op: BinOp, lhs: &SignalValue, rhs: &SignalValue, fmt: FloatFmt) -> SignalValue {
    let bool_val = |b: bool| SignalValue::from_u64(if b { 1 } else { 0 }, 1);
    match fmt {
        FloatFmt::F32 => {
            let (a, b) = match (lhs.as_f32(), rhs.as_f32()) {
                (Some(a), Some(b)) => (a, b),
                _ => return SignalValue::new(32),
            };
            match op {
                BinOp::Add => SignalValue::from_f32(a + b),
                BinOp::Sub => SignalValue::from_f32(a - b),
                BinOp::Mul => SignalValue::from_f32(a * b),
                BinOp::Div => SignalValue::from_f32(a / b),
                BinOp::Eq => bool_val(a == b),
                BinOp::Ne => bool_val(a != b),
                BinOp::Lt => bool_val(a < b),
                BinOp::Le => bool_val(a <= b),
                BinOp::Gt => bool_val(a > b),
                BinOp::Ge => bool_val(a >= b),
                _ => binop(op, lhs, rhs, false, false),
            }
        }
        FloatFmt::F64 => {
            let (a, b) = match (lhs.as_f64(), rhs.as_f64()) {
                (Some(a), Some(b)) => (a, b),
                _ => return SignalValue::new(64),
            };
            match op {
                BinOp::Add => SignalValue::from_f64(a + b),
                BinOp::Sub => SignalValue::from_f64(a - b),
                BinOp::Mul => SignalValue::from_f64(a * b),
                BinOp::Div => SignalValue::from_f64(a / b),
                BinOp::Eq => bool_val(a == b),
                BinOp::Ne => bool_val(a != b),
                BinOp::Lt => bool_val(a < b),
                BinOp::Le => bool_val(a <= b),
                BinOp::Gt => bool_val(a > b),
                BinOp::Ge => bool_val(a >= b),
                _ => binop(op, lhs, rhs, false, false),
            }
        }
    }
}

/// Apply a unary operator
pub fn unop(op: UnaryOp, value: &SignalValue) -> SignalValue {
    let width = value.width();
    let v = value.to_u64().unwrap_or(0);

    match op {
        UnaryOp::Neg => {
            let magnitude = value.to_i64().unwrap_or(v as i64);
            SignalValue::from_i64(-magnitude, width)
        }
        UnaryOp::Not => SignalValue::from_u64(!v, width),
        UnaryOp::LogNot => SignalValue::from_u64((v == 0) as u64, width),
    }
}

/// Join values into one, the first argument occupying the most significant bits
pub fn concat(parts: &[SignalValue]) -> SignalValue {
    let mut result: u64 = 0;
    let mut total_width: usize = 0;
    for part in parts {
        let width = part.width();
        let v = part.to_u64().unwrap_or(0);
        let mask = if width >= 64 {
            u64::MAX
        } else {
            (1u64 << width) - 1
        };
        result = (result << width) | (v & mask);
        total_width += width;
    }
    SignalValue::from_u64(result, total_width.max(1))
}

/// Take bits `[high:low]` of a value
pub fn slice(base: &SignalValue, high: usize, low: usize) -> SignalValue {
    let v = base.to_u64().unwrap_or(0);
    let width = high.saturating_sub(low) + 1;
    let mask = if width >= 64 {
        u64::MAX
    } else {
        (1u64 << width) - 1
    };
    SignalValue::from_u64((v >> low) & mask, width)
}

/// Take one bit of a value
pub fn bit(base: &SignalValue, index: usize) -> SignalValue {
    let v = base.to_u64().unwrap_or(0);
    SignalValue::from_u64((v >> index) & 1, 1)
}

/// Take a fixed-width field at a position that may vary (`base[index +: width]`)
pub fn part_select(base: &SignalValue, index: usize, width: usize, upward: bool) -> SignalValue {
    let width = width.max(1);
    let low = if upward {
        index
    } else {
        index.saturating_sub(width - 1)
    };
    slice(base, low + width - 1, low)
}

/// Replace the `width` bits starting at `low` in `base`
pub fn merge_field(base: &SignalValue, low: usize, width: usize, field: u64) -> SignalValue {
    let mask = if width >= 64 {
        u64::MAX
    } else {
        (1u64 << width) - 1
    };
    let merged = (base.to_u64().unwrap_or(0) & !(mask << low)) | ((field & mask) << low);
    SignalValue::from_u64(merged, base.width()).with_signed(base.is_signed())
}

/// Fit a value to a declared width, keeping the declaration's signedness.
///
/// Expression evaluation widens intermediate results, so a result has to be
/// fitted to its target before being stored. Without this a `bit[5]` counter
/// would keep counting past 31.
#[inline]
pub fn coerce(value: SignalValue, width: usize, signed: bool) -> SignalValue {
    if value.width() != width {
        SignalValue::from_u64(value.to_u64().unwrap_or(0), width).with_signed(signed)
    } else {
        value.with_signed(signed)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_unsized_literal_takes_the_other_operand_width() {
        let ptr = SignalValue::from_u64(31, 5);
        let one = SignalValue::from_u64(1, 32);
        let sum = binop(BinOp::Add, &ptr, &one, false, true);
        assert_eq!(sum.width(), 5);
        assert_eq!(sum.to_u64(), Some(0));
    }

    #[test]
    fn a_comparison_is_signed_only_when_both_sides_are() {
        let neg = SignalValue::from_i64(-50, 8);
        let pos = SignalValue::from_i64(30, 8);
        assert_eq!(binop(BinOp::Lt, &neg, &pos, false, false).to_u64(), Some(1));

        let raw = SignalValue::from_u64(30, 8);
        assert_eq!(binop(BinOp::Lt, &neg, &raw, false, false).to_u64(), Some(0));
    }

    #[test]
    fn a_field_write_leaves_the_other_bits_alone() {
        let reg = SignalValue::from_u64(0xff00, 16);
        let merged = merge_field(&reg, 0, 8, 0x5a);
        assert_eq!(merged.to_u64(), Some(0xff5a));
    }
}
