//! Wave tracer implementation for recording signal changes

use crate::SimTime;
use std::collections::HashMap;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

/// Signal change record
#[derive(Debug, Clone)]
struct SignalChange {
    time: SimTime,
    value: u64,
}

/// Signal definition
#[derive(Debug, Clone)]
struct SignalDef {
    #[allow(dead_code)]
    name: String,
    width: usize,
    changes: Vec<SignalChange>,
    last_value: Option<u64>,
}

/// Wave tracer for recording simulation waveforms
#[derive(Debug)]
pub struct WaveTracer {
    signals: HashMap<String, SignalDef>,
    signal_order: Vec<String>,
    timescale_ps: u64,
}

impl WaveTracer {
    /// Create a new wave tracer
    pub fn new() -> Self {
        Self {
            signals: HashMap::new(),
            signal_order: Vec::new(),
            timescale_ps: 1000, // 1ns default
        }
    }

    /// Set timescale in picoseconds
    pub fn set_timescale(&mut self, timescale_ps: u64) {
        self.timescale_ps = timescale_ps;
    }

    /// Register a signal for tracing
    pub fn register(&mut self, name: &str, width: usize) {
        if !self.signals.contains_key(name) {
            self.signals.insert(
                name.to_string(),
                SignalDef {
                    name: name.to_string(),
                    width,
                    changes: Vec::new(),
                    last_value: None,
                },
            );
            self.signal_order.push(name.to_string());
        }
    }

    /// Record a signal value at the given time (only if changed)
    pub fn record(&mut self, name: &str, time: SimTime, value: u64) {
        if let Some(signal) = self.signals.get_mut(name) {
            // Only record if value changed
            if signal.last_value != Some(value) {
                signal.changes.push(SignalChange { time, value });
                signal.last_value = Some(value);
            }
        }
    }

    /// Force record a signal value (even if not changed)
    pub fn record_force(&mut self, name: &str, time: SimTime, value: u64) {
        if let Some(signal) = self.signals.get_mut(name) {
            signal.changes.push(SignalChange { time, value });
            signal.last_value = Some(value);
        }
    }

    /// Get all signal names
    pub fn signal_names(&self) -> impl Iterator<Item = &str> {
        self.signal_order.iter().map(|s| s.as_str())
    }

    /// Write waveform to VCD file
    pub fn write_vcd<P: AsRef<Path>>(&self, path: P) -> std::io::Result<()> {
        let file = File::create(path)?;
        let mut writer = BufWriter::new(file);

        // Header
        writeln!(writer, "$date")?;
        writeln!(writer, "   Generated by iris-runtime")?;
        writeln!(writer, "$end")?;
        writeln!(writer, "$version")?;
        writeln!(writer, "   IRIS Runtime 0.1.0")?;
        writeln!(writer, "$end")?;
        writeln!(writer, "$timescale")?;
        writeln!(writer, "   1ps")?;
        writeln!(writer, "$end")?;

        // Scope
        writeln!(writer, "$scope module top $end")?;

        // Signal definitions
        let mut id_map: HashMap<&str, char> = HashMap::new();
        let mut current_id = '!';

        for name in &self.signal_order {
            if let Some(signal) = self.signals.get(name) {
                id_map.insert(name, current_id);
                if signal.width == 1 {
                    writeln!(writer, "$var wire 1 {} {} $end", current_id, name)?;
                } else {
                    writeln!(
                        writer,
                        "$var wire {} {} {} [{}:0] $end",
                        signal.width,
                        current_id,
                        name,
                        signal.width - 1
                    )?;
                }
                current_id = (current_id as u8 + 1) as char;
            }
        }

        writeln!(writer, "$upscope $end")?;
        writeln!(writer, "$enddefinitions $end")?;

        // Collect all time points
        let mut all_times: Vec<SimTime> = self
            .signals
            .values()
            .flat_map(|s| s.changes.iter().map(|c| c.time))
            .collect();
        all_times.sort();
        all_times.dedup();

        // Write value changes
        let mut current_time = u64::MAX;
        for time in all_times {
            if time != current_time {
                writeln!(writer, "#{}", time)?;
                current_time = time;
            }

            for name in &self.signal_order {
                if let Some(signal) = self.signals.get(name) {
                    if let Some(change) = signal.changes.iter().find(|c| c.time == time) {
                        let id = id_map.get(name.as_str()).unwrap();
                        if signal.width == 1 {
                            writeln!(writer, "{}{}", change.value & 1, id)?;
                        } else {
                            writeln!(writer, "b{:b} {}", change.value, id)?;
                        }
                    }
                }
            }
        }

        writer.flush()?;
        Ok(())
    }
}

impl Default for WaveTracer {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tracer_basic() {
        let mut tracer = WaveTracer::new();
        tracer.register("clk", 1);
        tracer.register("count", 8);

        tracer.record("clk", 0, 0);
        tracer.record("count", 0, 0);
        tracer.record("clk", 5000, 1);
        tracer.record("count", 5000, 1);
        tracer.record("clk", 10000, 0);

        assert_eq!(tracer.signal_names().count(), 2);
    }

    #[test]
    fn test_tracer_dedup() {
        let mut tracer = WaveTracer::new();
        tracer.register("sig", 1);

        tracer.record("sig", 0, 0);
        tracer.record("sig", 1000, 0); // same value, should not record
        tracer.record("sig", 2000, 1); // different value

        let changes = &tracer.signals.get("sig").unwrap().changes;
        assert_eq!(changes.len(), 2);
    }
}
