//! What iris2sv converts, and how.

use iris2sv::transpile;

#[test]
fn a_combinational_adder_converts() {
    let sv = transpile(
        "mod Add(in a: bit[8], in b: bit[8], out y: bit[8],) { comb { y = a + b; } }",
    )
    .expect("should convert");
    assert!(sv.contains("// Generated by iris2sv"), "{}", sv);
    assert!(sv.contains("module Add ("), "{}", sv);
    assert!(sv.contains("input  logic [7:0] a,"), "{}", sv);
    assert!(sv.contains("output logic [7:0] y"), "{}", sv);
    // A binary operation is size-cast to the target width.
    assert!(sv.contains("y = 8'(a + b);"), "{}", sv);
    assert!(sv.contains("endmodule"), "{}", sv);
}

#[test]
fn a_simple_copy_and_sized_literal_are_not_cast() {
    let sv = transpile(
        "mod T(in a: bit[8], out y: bit[8], out w: bit[8],) { comb { y = a; w = 8'd5; } }",
    )
    .expect("should convert");
    assert!(sv.contains("y = a;"), "{}", sv);
    assert!(sv.contains("w = 8'd5;"), "{}", sv);
    // Multiple statements use begin/end.
    assert!(sv.contains("always_comb begin"), "{}", sv);
}

#[test]
fn a_one_bit_port_is_plain_logic() {
    let sv = transpile("mod M(in a: bit, out y: bit,) { comb { y = a; } }")
        .expect("should convert");
    assert!(sv.contains("input  logic a,"), "{}", sv);
    assert!(sv.contains("output logic y"), "{}", sv);
}

#[test]
fn a_match_expression_becomes_a_ternary_chain() {
    let sv = transpile(
        "mod M(in op: bit[2], in a: bit[8], in b: bit[8], out y: bit[8],) {\n\
         comb { y = match op { 2'd0 => a + b, 2'd1 => a - b, _ => a }; }\n}",
    )
    .expect("should convert");
    assert!(sv.contains("y = op == 2'd0 ? 8'(a + b) : op == 2'd1 ? 8'(a - b) : a;"), "{}", sv);
}

#[test]
fn a_sync_block_and_memory_convert() {
    let sv = transpile(
        "mod M(in clk: clock, in we: bit, in addr: bit[5], in d: bit[32], out q: bit[32],) {\n\
         mem regs: bit[32][32];\n\
         sync(clk.posedge) { if we { regs[addr] = d; } }\n\
         comb { q = regs[addr]; }\n}",
    )
    .expect("should convert");
    assert!(sv.contains("logic [31:0] regs [32];"), "{}", sv);
    assert!(sv.contains("always_ff @(posedge clk)"), "{}", sv);
    assert!(sv.contains("regs[addr] <= d;"), "{}", sv);
    assert!(sv.contains("q = regs[addr];"), "{}", sv);
}

#[test]
fn a_sign_extend_method_becomes_a_signed_cast() {
    let sv = transpile(
        "mod M(in a: bit[16], out y: bit[32],) { comb { y = a.sign_extend[32](); } }",
    )
    .expect("should convert");
    assert!(sv.contains("y = 32'($signed(a));"), "{}", sv);
}

#[test]
fn a_parameter_and_param_depth_memory_convert() {
    let sv = transpile(
        "mod M[N: uint = 1024,](in a: bit[5], out y: bit[32],) {\n\
         mem ram: bit[32][N];\n\
         comb { y = ram[a]; }\n}",
    )
    .expect("should convert");
    assert!(sv.contains("module M #("), "{}", sv);
    assert!(sv.contains("parameter logic [31:0] N = 'h400"), "{}", sv);
    assert!(sv.contains("logic [31:0] ram [N];"), "{}", sv);
}

#[test]
fn an_instance_converts() {
    let sv = transpile(
        "mod Top(in a: bit[8], out y: bit[8],) {\n\
         inst u = Sub { x: a, o: y };\n\
         comb { y = a; }\n}",
    )
    .expect("should convert");
    assert!(sv.contains("Sub u ("), "{}", sv);
    assert!(sv.contains(".x(a),"), "{}", sv);
    assert!(sv.contains(".o(y)"), "{}", sv);
}

#[test]
fn a_reset_expands_into_a_reset_branch() {
    let sv = transpile(
        "mod M(in clk: clock, in rst_n: reset(active_low: true), in en: bit, out q: bit[8],) {\n\
         var cnt: bit[8] = 0;\n\
         sync(clk.posedge, rst_n.async) { if en { cnt = cnt + 1; } }\n\
         comb { q = cnt; }\n}",
    )
    .expect("should convert");
    assert!(sv.contains("always_ff @(posedge clk or negedge rst_n)"), "{}", sv);
    assert!(sv.contains("if (!rst_n) "), "{}", sv);
    assert!(sv.contains("cnt <= 0;"), "{}", sv);
    assert!(sv.contains("else if (en) "), "{}", sv);
}

#[test]
fn an_enum_and_named_type_and_match_convert() {
    let sv = transpile(
        "enum Op { Add, Sub, And }\n\
         mod M(in s: bit[2], out y: bit[8],) {\n\
         var op: Op = Op::Add;\n\
         comb { y = match op { Op::Add => 8'd1, Op::Sub => 8'd2, Op::And => 8'd3 }; }\n}",
    )
    .expect("should convert");
    assert!(sv.contains("typedef enum logic [1:0] {"), "{}", sv);
    assert!(sv.contains("Add = 0,"), "{}", sv);
    assert!(sv.contains("} Op;"), "{}", sv);
    assert!(sv.contains("Op op = Add;"), "{}", sv);
    // Exhaustive match: last arm is the else, members unqualified.
    assert!(sv.contains("y = op == Add ? 8'd1 : op == Sub ? 8'd2 : 8'd3;"), "{}", sv);
}

#[test]
fn a_struct_a_function_and_an_interface_convert() {
    let sv = transpile(
        "struct Packet { valid: bit, data: bit[8] }\n\
         fn add(a: bit[8], b: bit[8]) -> bit[8] { return a + b; }\n\
         interface Bus { valid: bit, ready: bit, view m { out: valid, in: ready } }\n\
         mod M(out y: bit,) { comb { y = 0; } }",
    )
    .expect("should convert");
    assert!(sv.contains("typedef struct packed {"), "{}", sv);
    assert!(sv.contains("logic valid;"), "{}", sv);
    assert!(sv.contains("function automatic logic [7:0] add(input logic [7:0] a, input logic [7:0] b);"), "{}", sv);
    assert!(sv.contains("return 8'(a + b);"), "{}", sv);
    assert!(sv.contains("interface Bus;"), "{}", sv);
    assert!(sv.contains("modport m (output valid, input ready);"), "{}", sv);
}

#[test]
fn parametric_widths_and_clog2_convert() {
    let sv = transpile(
        "mod F[DataWidth: uint = 8, Depth: uint = 16, AddrWidth: uint = $clog2(Depth),](\n\
         in wr_data: bit[DataWidth], out rd_data: bit[DataWidth],) {\n\
         mem storage: bit[DataWidth][Depth];\n\
         comb { rd_data = wr_data; }\n}",
    )
    .expect("should convert");
    assert!(sv.contains("parameter logic [31:0] DataWidth = 8"), "{}", sv);
    assert!(sv.contains("parameter logic [31:0] AddrWidth = $clog2(Depth)"), "{}", sv);
    assert!(sv.contains("input  logic [DataWidth-1:0] wr_data,"), "{}", sv);
    assert!(sv.contains("logic [DataWidth-1:0] storage [Depth];"), "{}", sv);
}
