// Generated by iris2sv
// Do not edit manually

module Alu (
  input  logic [3:0]  op,
  input  logic [31:0] a,
  input  logic [31:0] b,
  output logic [31:0] y
);

// Internal signals
  logic signed [31:0] sa = 0;
  logic signed [31:0] sb = 0;
  logic [4:0] shamt = 0;
  logic signed [31:0] sra_result = 0;

  always_comb begin
    sa = a;
    sb = b;
    shamt = b[4:0];
    sra_result = sa >>> shamt;
    y = op == 4'd0 ? 32'(a + b) : op == 4'd1 ? 32'(a - b) : op == 4'd2 ? 32'(a << shamt) : op == 4'd3 ? sa < sb ? 32'h1 : 32'h0 : op == 4'd4 ? a < b ? 32'h1 : 32'h0 : op == 4'd5 ? a ^ b : op == 4'd6 ? a >> shamt : op == 4'd7 ? sra_result : op == 4'd8 ? a | b : op == 4'd9 ? a & b : 32'h0;
  end

endmodule

