// Generated by iris2sv
// Do not edit manually

module Decoder (
  input  logic [31:0] instr,
  output logic [4:0]  rd,
  output logic [4:0]  rs1,
  output logic [4:0]  rs2,
  output logic [2:0]  funct3,
  output logic [31:0] imm,
  output logic [3:0]  alu_op,
  output logic        alu_a_pc,
  output logic        alu_b_imm,
  output logic        reg_write,
  output logic        mem_read,
  output logic        mem_write,
  output logic        is_branch,
  output logic        is_jal,
  output logic        is_jalr,
  output logic        is_lui,
  output logic        is_system,
  output logic        is_fence,
  output logic        illegal
);

// Internal signals
  logic [6:0] opcode = 0;
  logic [6:0] funct7 = 0;
  logic [31:0] imm_i = 0;
  logic [31:0] imm_s = 0;
  logic [31:0] imm_b = 0;
  logic [31:0] imm_u = 0;
  logic [31:0] imm_j = 0;
  logic [3:0] alu_rtype = 0;
  logic [3:0] alu_itype = 0;

  always_comb begin
    opcode = instr[6:0];
    funct7 = instr[31:25];
    rd = instr[11:7];
    funct3 = instr[14:12];
    rs1 = instr[19:15];
    rs2 = instr[24:20];
    imm_i = 32'($signed(instr[31:20]));
    imm_s = 32'($signed({instr[31:25], instr[11:7]}));
    imm_b = 32'($signed({instr[31], instr[7], instr[30:25], instr[11:8], 1'd0}));
    imm_u = {instr[31:12], 12'h0};
    imm_j = 32'($signed({instr[31], instr[19:12], instr[20], instr[30:21], 1'd0}));
    imm = opcode == 7'd19 ? imm_i : opcode == 7'd3 ? imm_i : opcode == 7'd103 ? imm_i : opcode == 7'd115 ? imm_i : opcode == 7'd35 ? imm_s : opcode == 7'd99 ? imm_b : opcode == 7'd55 ? imm_u : opcode == 7'd23 ? imm_u : opcode == 7'd111 ? imm_j : 32'h0;
    alu_rtype = funct3 == 3'd0 ? funct7[5] ? 4'd1 : 4'd0 : funct3 == 3'd1 ? 4'd2 : funct3 == 3'd2 ? 4'd3 : funct3 == 3'd3 ? 4'd4 : funct3 == 3'd4 ? 4'd5 : funct3 == 3'd5 ? funct7[5] ? 4'd7 : 4'd6 : funct3 == 3'd6 ? 4'd8 : 4'd9;
    alu_itype = funct3 == 3'd0 ? 4'd0 : funct3 == 3'd1 ? 4'd2 : funct3 == 3'd2 ? 4'd3 : funct3 == 3'd3 ? 4'd4 : funct3 == 3'd4 ? 4'd5 : funct3 == 3'd5 ? funct7[5] ? 4'd7 : 4'd6 : funct3 == 3'd6 ? 4'd8 : 4'd9;
    alu_op = opcode == 7'd51 ? alu_rtype : opcode == 7'd19 ? alu_itype : 4'd0;
    alu_a_pc = opcode == 7'd23 ? 1'd1 : opcode == 7'd111 ? 1'd1 : 1'd0;
    alu_b_imm = opcode == 7'd19 ? 1'd1 : opcode == 7'd3 ? 1'd1 : opcode == 7'd35 ? 1'd1 : opcode == 7'd103 ? 1'd1 : opcode == 7'd23 ? 1'd1 : opcode == 7'd111 ? 1'd1 : 1'd0;
    reg_write = opcode == 7'd51 ? 1'd1 : opcode == 7'd19 ? 1'd1 : opcode == 7'd3 ? 1'd1 : opcode == 7'd111 ? 1'd1 : opcode == 7'd103 ? 1'd1 : opcode == 7'd55 ? 1'd1 : opcode == 7'd23 ? 1'd1 : 1'd0;
    mem_read = opcode == 7'd3 ? 1'd1 : 1'd0;
    mem_write = opcode == 7'd35 ? 1'd1 : 1'd0;
    is_branch = opcode == 7'd99 ? 1'd1 : 1'd0;
    is_jal = opcode == 7'd111 ? 1'd1 : 1'd0;
    is_jalr = opcode == 7'd103 ? 1'd1 : 1'd0;
    is_lui = opcode == 7'd55 ? 1'd1 : 1'd0;
    is_fence = opcode == 7'd15 ? 1'd1 : 1'd0;
    is_system = opcode == 7'd115 ? funct3 == 3'd0 ? 1'd1 : 1'd0 : 1'd0;
    illegal = opcode == 7'd51 ? 1'd0 : opcode == 7'd19 ? 1'd0 : opcode == 7'd3 ? 1'd0 : opcode == 7'd35 ? 1'd0 : opcode == 7'd99 ? 1'd0 : opcode == 7'd111 ? 1'd0 : opcode == 7'd103 ? 1'd0 : opcode == 7'd55 ? 1'd0 : opcode == 7'd23 ? 1'd0 : opcode == 7'd15 ? 1'd0 : opcode == 7'd115 ? 1'd0 : 1'd1;
  end

endmodule

