// Generated by iris2sv
// Do not edit manually

module RegFile (
  input  logic        clk,
  input  logic        rst_n,
  input  logic        we,
  input  logic [4:0]  waddr,
  input  logic [31:0] wdata,
  input  logic [4:0]  raddr1,
  input  logic [4:0]  raddr2,
  output logic [31:0] rdata1,
  output logic [31:0] rdata2,
  input  logic [4:0]  dbg_addr,
  output logic [31:0] dbg_data
);

// Internal signals
  logic [31:0] regs [32];

  always_comb begin
    rdata1 = raddr1 == 5'd0 ? 32'h0 : regs[raddr1];
    rdata2 = raddr2 == 5'd0 ? 32'h0 : regs[raddr2];
    dbg_data = dbg_addr == 5'd0 ? 32'h0 : regs[dbg_addr];
  end

  always_ff @(posedge clk or negedge rst_n) 
    if (we) 
      if (waddr != 5'd0) 
        regs[waddr] <= wdata;

endmodule

