// Generated by iris2sv
// Do not edit manually

module RiscvCore #(
  parameter logic [31:0] DataWords = 'h400
) (
  input  logic        clk,
  input  logic        rst_n,
  output logic [31:0] imem_addr,
  input  logic [31:0] imem_rdata,
  output logic [31:0] pc_out,
  output logic        halted,
  output logic        illegal_op,
  input  logic [4:0]  dbg_addr,
  output logic [31:0] dbg_data
);

// Internal signals
  logic [31:0] pc = 0;
  logic halt_reg = 0;
  logic illegal_reg = 0;
  logic [31:0] dmem [DataWords];
  logic wb_en = 0;
  logic [31:0] wb_data = 0;
  logic [31:0] alu_a = 0;
  logic [31:0] alu_b = 0;
  logic signed [31:0] s_rs1 = 0;
  logic signed [31:0] s_rs2 = 0;
  logic branch_taken = 0;
  logic [31:0] alu_y = 0;
  logic [31:0] src2 = 0;
  logic [31:0] mem_word_addr = 0;
  logic [1:0] mem_byte_sel = 0;
  logic [31:0] mem_rword = 0;
  logic [7:0] load_byte = 0;
  logic [15:0] load_half = 0;
  logic [31:0] load_data = 0;
  logic [31:0] store_word = 0;
  logic [31:0] pc_plus4 = 0;
  logic [31:0] jalr_target = 0;
  logic [31:0] next_pc = 0;
  logic is_ecall_or_ebreak = 0;

  always_comb begin
    imem_addr = pc;
    pc_out = pc;
    halted = halt_reg;
    illegal_op = illegal_reg;
    dbg_data = rf.dbg_data;
    pc_plus4 = 32'(pc + 32'h4);
    alu_a = dec.alu_a_pc ? pc : rf.rdata1;
    alu_b = dec.alu_b_imm ? dec.imm : rf.rdata2;
    s_rs1 = rf.rdata1;
    s_rs2 = rf.rdata2;
    branch_taken = dec.is_branch ? dec.funct3 == 3'd0 ? rf.rdata1 == rf.rdata2 ? 1'd1 : 1'd0 : dec.funct3 == 3'd1 ? rf.rdata1 != rf.rdata2 ? 1'd1 : 1'd0 : dec.funct3 == 3'd4 ? s_rs1 < s_rs2 ? 1'd1 : 1'd0 : dec.funct3 == 3'd5 ? s_rs1 < s_rs2 ? 1'd0 : 1'd1 : dec.funct3 == 3'd6 ? rf.rdata1 < rf.rdata2 ? 1'd1 : 1'd0 : dec.funct3 == 3'd7 ? rf.rdata1 < rf.rdata2 ? 1'd0 : 1'd1 : 1'd0 : 1'd0;
    alu_y = alu.y;
    src2 = rf.rdata2;
    mem_word_addr = alu_y >> 2;
    mem_byte_sel = alu_y[1:0];
    mem_rword = dmem[mem_word_addr];
    load_byte = mem_byte_sel == 2'd0 ? mem_rword[7:0] : mem_byte_sel == 2'd1 ? mem_rword[15:8] : mem_byte_sel == 2'd2 ? mem_rword[23:16] : mem_rword[31:24];
    load_half = mem_byte_sel[1] ? mem_rword[31:16] : mem_rword[15:0];
    load_data = dec.funct3 == 3'd0 ? 32'($signed(load_byte)) : dec.funct3 == 3'd1 ? 32'($signed(load_half)) : dec.funct3 == 3'd2 ? mem_rword : dec.funct3 == 3'd4 ? 32'(load_byte) : dec.funct3 == 3'd5 ? 32'(load_half) : mem_rword;
    store_word = dec.funct3 == 3'd0 ? mem_byte_sel == 2'd0 ? {mem_rword[31:8], src2[7:0]} : mem_byte_sel == 2'd1 ? {mem_rword[31:16], src2[7:0], mem_rword[7:0]} : mem_byte_sel == 2'd2 ? {mem_rword[31:24], src2[7:0], mem_rword[15:0]} : {src2[7:0], mem_rword[23:0]} : dec.funct3 == 3'd1 ? mem_byte_sel[1] ? {src2[15:0], mem_rword[15:0]} : {mem_rword[31:16], src2[15:0]} : src2;
    jalr_target = rf.rdata1 + dec.imm & 32'hfffffffe;
    wb_data = dec.is_lui ? dec.imm : dec.mem_read ? load_data : dec.is_jal ? pc_plus4 : dec.is_jalr ? pc_plus4 : alu_y;
    wb_en = halt_reg ? 1'd0 : dec.reg_write;
    is_ecall_or_ebreak = dec.is_system;
    next_pc = branch_taken ? 32'(pc + dec.imm) : dec.is_jal ? alu_y : dec.is_jalr ? jalr_target : pc_plus4;
  end

  always_ff @(posedge clk or negedge rst_n) 
    if (~rst_n) begin
      pc <= 0;
      halt_reg <= 0;
      illegal_reg <= 0;
    end
    else if (~halt_reg) 
      if (is_ecall_or_ebreak) 
        halt_reg <= 1;
      else if (dec.illegal) begin
        illegal_reg <= 1;
        halt_reg <= 1;
      end
      else begin
        if (dec.mem_write) 
          dmem[mem_word_addr] <= store_word;
        pc <= next_pc;
      end


// Module instances
  Decoder dec (
    .instr(imem_rdata)
  );

  RegFile rf (
    .clk(clk),
    .rst_n(rst_n),
    .we(wb_en),
    .waddr(dec.rd),
    .wdata(wb_data),
    .raddr1(dec.rs1),
    .raddr2(dec.rs2),
    .dbg_addr(dbg_addr)
  );

  Alu alu (
    .op(dec.alu_op),
    .a(alu_a),
    .b(alu_b)
  );

endmodule

