// Generated by iris2sv
// Do not edit manually

module RomSys (
  input  logic [31:0] addr,
  output logic [31:0] rdata
);

  always_comb 
    rdata = addr[9:2] == 8'd0 ? 32'h100093 : addr[9:2] == 8'd1 ? 32'hff0000f : addr[9:2] == 8'd2 ? 32'h200113 : addr[9:2] == 8'd3 ? 32'h73 : addr[9:2] == 8'd4 ? 32'h6300193 : 32'h13;

endmodule

