// Generated by iris2sv
// Do not edit manually

module RomAlu (
  input  logic [31:0] addr,
  output logic [31:0] rdata
);

  always_comb 
    rdata = addr[9:2] == 8'd0 ? 32'hc00093 : addr[9:2] == 8'd1 ? 32'h500113 : addr[9:2] == 8'd2 ? 32'hff000f93 : addr[9:2] == 8'd3 ? 32'h2081b3 : addr[9:2] == 8'd4 ? 32'h40208233 : addr[9:2] == 8'd5 ? 32'h2112b3 : addr[9:2] == 8'd6 ? 32'h112333 : addr[9:2] == 8'd7 ? 32'h20b3b3 : addr[9:2] == 8'd8 ? 32'h20c433 : addr[9:2] == 8'd9 ? 32'h2fd4b3 : addr[9:2] == 8'd10 ? 32'h402fd533 : addr[9:2] == 8'd11 ? 32'h20e5b3 : addr[9:2] == 8'd12 ? 32'h20f633 : addr[9:2] == 8'd13 ? 32'hfff08693 : addr[9:2] == 8'd14 ? 32'hfa713 : addr[9:2] == 8'd15 ? 32'hfb793 : addr[9:2] == 8'd16 ? 32'hfff0c813 : addr[9:2] == 8'd17 ? 32'h30e893 : addr[9:2] == 8'd18 ? 32'h60f913 : addr[9:2] == 8'd19 ? 32'h409993 : addr[9:2] == 8'd20 ? 32'h4fda13 : addr[9:2] == 8'd21 ? 32'h404fda93 : addr[9:2] == 8'd22 ? 32'h12345b37 : addr[9:2] == 8'd23 ? 32'h100073 : 32'h13;

endmodule

