//! Rust code generator for IRIS modules

use crate::parser::ast::{
    BinOp, CombBlock, Expression, Instance, Literal, LogicBlock, Module,
    PortDirection, Statement, SyncBlock, Type, UnaryOp,
};
use crate::project::Project;
use std::collections::HashMap;
use thiserror::Error;

/// Code generation error
#[derive(Debug, Error)]
pub enum CodeGenError {
    #[error("Unsupported feature: {0}")]
    UnsupportedFeature(String),
    #[error("Invalid type: {0}")]
    InvalidType(String),
    #[error("Unknown signal: {0}")]
    UnknownSignal(String),
}

/// Rust code generator
pub struct RustCodeGenerator {
    output: String,
    indent: usize,
    signals: Vec<(String, usize)>, // (name, width)
}

impl RustCodeGenerator {
    /// Create a new code generator
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
        signals: Vec::new(),
        }
    }

    /// Generate Rust code from an IRIS module
    pub fn generate(&mut self, module: &Module) -> Result<String, CodeGenError> {
        self.output.clear();
        self.signals.clear();
        self.indent = 0;

        // Collect all signals
        self.collect_signals(module);

        // Generate header
        self.generate_header(module);

        // Generate main function
        self.generate_main(module)?;

        Ok(self.output.clone())
    }

    /// Collect all signals from the module
    fn collect_signals(&mut self, module: &Module) {
        // Ports
        for port in &module.ports {
            let width = self.type_to_width(&port.ty);
            self.signals.push((port.name.clone(), width));
        }

        // Internal signals
        for signal in &module.signals {
            let width = self.type_to_width(&signal.ty);
            self.signals.push((signal.name.clone(), width));
        }
    }

    /// Get bit width from type
    fn type_to_width(&self, ty: &Type) -> usize {
        match ty {
            Type::Bit => 1,
            Type::BitVec { width } => *width,
            Type::Clock => 1,
            Type::Reset { .. } => 1,
            Type::Array { element, size } => self.type_to_width(element) * size,
            Type::Named(_) => 32, // default
        }
    }

    /// Get Rust type for IRIS type
    fn type_to_rust(&self, ty: &Type) -> String {
        match ty {
            Type::Bit => "u8".to_string(),
            Type::BitVec { width } => {
                if *width <= 8 {
                    "u8".to_string()
                } else if *width <= 16 {
                    "u16".to_string()
                } else if *width <= 32 {
                    "u32".to_string()
                } else {
                    "u64".to_string()
                }
            }
            Type::Clock => "bool".to_string(),
            Type::Reset { .. } => "bool".to_string(),
            Type::Array { element, size } => {
                format!("[{}; {}]", self.type_to_rust(element), size)
            }
            Type::Named(_) => "u32".to_string(),
        }
    }

    /// Get bit mask for width
    fn width_to_mask(&self, width: usize) -> String {
        if width >= 64 {
            "u64::MAX".to_string()
        } else {
            format!("0x{:x}", (1u64 << width) - 1)
        }
    }

    /// Write a line with indentation
    fn writeln(&mut self, line: &str) {
        let indent_str = "    ".repeat(self.indent);
        self.output.push_str(&indent_str);
        self.output.push_str(line);
        self.output.push('\n');
    }

    /// Generate file header
    fn generate_header(&mut self, module: &Module) {
        self.writeln("//! Auto-generated IRIS simulation code");
        self.writeln(&format!("//! Module: {}", module.name));
        self.writeln("//!");
        self.writeln("//! This file was generated by iris-compile.");
        self.writeln("//! Do not edit manually.");
        self.writeln("");
        self.writeln("use iris_runtime::{Clock, Reset, WaveTracer};");
        self.writeln("use std::env;");
        self.writeln("");
    }

    /// Generate main function
    fn generate_main(&mut self, module: &Module) -> Result<(), CodeGenError> {
        self.writeln("fn main() {");
        self.indent += 1;

        // Parse command line arguments
        self.writeln("let args: Vec<String> = env::args().collect();");
        self.writeln("let cycles: u64 = args.get(1)");
        self.indent += 1;
        self.writeln(".and_then(|s| s.parse().ok())");
        self.writeln(".unwrap_or(100);");
        self.indent -= 1;
        self.writeln("let output_path = args.get(2)");
        self.indent += 1;
        self.writeln(".map(|s| s.as_str())");
        self.writeln(&format!(".unwrap_or(\"{}.vcd\");", module.name.to_lowercase()));
        self.indent -= 1;
        self.writeln("");

        // Generate signal declarations
        self.generate_signal_declarations(module)?;

        // Generate wave tracer setup
        self.generate_tracer_setup(module)?;

        // Generate reset sequence
        self.generate_reset_sequence(module)?;

        // Generate main simulation loop
        self.generate_simulation_loop(module)?;

        // Generate waveform output
        self.generate_waveform_output(module)?;

        // Generate summary output
        self.writeln("");
        self.writeln("println!(\"Simulation completed: {} cycles\", cycles);");

        self.indent -= 1;
        self.writeln("}");

        Ok(())
    }

    /// Generate signal declarations
    fn generate_signal_declarations(&mut self, module: &Module) -> Result<(), CodeGenError> {
        self.writeln("// Clock and reset");
        self.writeln("let mut clk = Clock::new(10_000); // 10ns period");
        self.writeln("let mut rst = Reset::new();");
        self.writeln("");

        self.writeln("// Signal declarations");

        // Ports (excluding clock/reset)
        for port in &module.ports {
            if matches!(port.ty, Type::Clock | Type::Reset { .. }) {
                continue;
            }
            let rust_type = self.type_to_rust(&port.ty);
            let init = if let Some(ref expr) = self.find_signal_init(module, &port.name) {
                self.generate_expression(expr)?
            } else {
                "0".to_string()
            };
            self.writeln(&format!("let mut {}: {} = {};", port.name, rust_type, init));
        }

        // Internal signals
        for signal in &module.signals {
            let rust_type = self.type_to_rust(&signal.ty);
            let init = if let Some(ref expr) = signal.init_value {
                self.generate_expression(expr)?
            } else {
                "0".to_string()
            };
            self.writeln(&format!("let mut {}: {} = {};", signal.name, rust_type, init));
        }

        self.writeln("");
        Ok(())
    }

    /// Find initial value for a signal
    fn find_signal_init(&self, _module: &Module, _name: &str) -> Option<Expression> {
        None // Ports don't have initial values in this context
    }

    /// Generate wave tracer setup
    fn generate_tracer_setup(&mut self, module: &Module) -> Result<(), CodeGenError> {
        self.writeln("// Wave tracer setup");
        self.writeln("let mut tracer = WaveTracer::new();");
        self.writeln("tracer.register(\"clk\", 1);");
        self.writeln("tracer.register(\"rst\", 1);");

        for port in &module.ports {
            if matches!(port.ty, Type::Clock | Type::Reset { .. }) {
                continue;
            }
            let width = self.type_to_width(&port.ty);
            self.writeln(&format!("tracer.register(\"{}\", {});", port.name, width));
        }

        for signal in &module.signals {
            let width = self.type_to_width(&signal.ty);
            self.writeln(&format!("tracer.register(\"{}\", {});", signal.name, width));
        }

        self.writeln("");
        Ok(())
    }

    /// Generate reset sequence
    fn generate_reset_sequence(&mut self, _module: &Module) -> Result<(), CodeGenError> {
        self.writeln("// Reset sequence");
        self.writeln("rst.assert();");
        self.writeln("for _ in 0..4 {  // Even number of ticks to end with clock low");
        self.indent += 1;
        self.writeln("clk.tick();");
        self.writeln("tracer.record(\"clk\", clk.get_time(), clk.as_u64());");
        self.writeln("tracer.record(\"rst\", clk.get_time(), rst.as_u64());");
        self.indent -= 1;
        self.writeln("}");
        self.writeln("rst.deassert();");
        self.writeln("");
        Ok(())
    }

    /// Generate main simulation loop
    fn generate_simulation_loop(&mut self, module: &Module) -> Result<(), CodeGenError> {
        self.writeln("// Main simulation loop");
        self.writeln("for _cycle in 0..cycles {");
        self.indent += 1;

        // Generate clock tick (rising edge)
        self.writeln("clk.tick(); // Rising edge");
        self.writeln("");

        // Generate posedge evaluation
        self.writeln("// Posedge evaluation");
        self.writeln("if clk.posedge() {");
        self.indent += 1;

        for block in &module.logic_blocks {
            if let LogicBlock::Sync(sync) = block {
                self.generate_sync_block(sync)?;
            }
        }

        self.indent -= 1;
        self.writeln("}");
        self.writeln("");

        // Generate combinational logic
        self.writeln("// Combinational logic");
        for block in &module.logic_blocks {
            if let LogicBlock::Comb(comb) = block {
                self.generate_comb_block(comb)?;
            }
        }
        self.writeln("");

        // Record signal values
        self.generate_value_recording(module)?;

        // Generate clock tick (falling edge)
        self.writeln("clk.tick(); // Falling edge");

        self.indent -= 1;
        self.writeln("}");
        self.writeln("");

        Ok(())
    }

    /// Generate sync block code
    fn generate_sync_block(&mut self, sync: &SyncBlock) -> Result<(), CodeGenError> {
        // Check for async reset
        if sync.reset.is_some() {
            self.writeln("if rst.is_active() {");
            self.indent += 1;

            // Reset values
            for stmt in &sync.statements {
                if let Statement::Assign { target, value: _ } = stmt {
                    // Find the signal and use its default value
                    self.writeln(&format!("{} = 0;", target));
                }
            }

            self.indent -= 1;
            self.writeln("} else {");
            self.indent += 1;
        }

        // Normal operation
        for stmt in &sync.statements {
            self.generate_statement(stmt)?;
        }

        if sync.reset.is_some() {
            self.indent -= 1;
            self.writeln("}");
        }

        Ok(())
    }

    /// Generate comb block code
    fn generate_comb_block(&mut self, comb: &CombBlock) -> Result<(), CodeGenError> {
        for stmt in &comb.statements {
            self.generate_statement(stmt)?;
        }
        Ok(())
    }

    /// Generate statement code
    fn generate_statement(&mut self, stmt: &Statement) -> Result<(), CodeGenError> {
        match stmt {
            Statement::Assign { target, value } => {
                let value_code = self.generate_expression(value)?;

                // Find signal width for masking
                if let Some((_, width)) = self.signals.iter().find(|(n, _)| n == target) {
                    if *width < 64 {
                        let mask = self.width_to_mask(*width);
                        self.writeln(&format!("{} = ({}) & {};", target, value_code, mask));
                    } else {
                        self.writeln(&format!("{} = {};", target, value_code));
                    }
                } else {
                    self.writeln(&format!("{} = {};", target, value_code));
                }
            }
            Statement::If {
                condition,
                then_branch,
                else_branch,
            } => {
                let cond_code = self.generate_expression(condition)?;
                self.writeln(&format!("if {} != 0 {{", cond_code));
                self.indent += 1;
                for s in then_branch {
                    self.generate_statement(s)?;
                }
                self.indent -= 1;
                if let Some(else_stmts) = else_branch {
                    self.writeln("} else {");
                    self.indent += 1;
                    for s in else_stmts {
                        self.generate_statement(s)?;
                    }
                    self.indent -= 1;
                }
                self.writeln("}");
            }
            Statement::Match { .. } => {
                return Err(CodeGenError::UnsupportedFeature("match statement".to_string()));
            }
            Statement::For { var, range, body } => {
                let start = self.generate_expression(&range.start)?;
                let end = self.generate_expression(&range.end)?;
                let range_op = if range.inclusive { "..=" } else { ".." };
                self.writeln(&format!("for {} in {}{}{} {{", var, start, range_op, end));
                self.indent += 1;
                for s in body {
                    self.generate_statement(s)?;
                }
                self.indent -= 1;
                self.writeln("}");
            }
            Statement::While { condition, body } => {
                let cond_code = self.generate_expression(condition)?;
                self.writeln(&format!("while {} != 0 {{", cond_code));
                self.indent += 1;
                for s in body {
                    self.generate_statement(s)?;
                }
                self.indent -= 1;
                self.writeln("}");
            }
        }
        Ok(())
    }

    /// Generate expression code
    fn generate_expression(&self, expr: &Expression) -> Result<String, CodeGenError> {
        match expr {
            Expression::Literal(lit) => self.generate_literal(lit),
            Expression::Ident(name) => Ok(name.clone()),
            Expression::BinOp { op, lhs, rhs } => {
                let lhs_code = self.generate_expression(lhs)?;
                let rhs_code = self.generate_expression(rhs)?;
                let op_str = self.binop_to_rust(op);
                Ok(format!("({} {} {})", lhs_code, op_str, rhs_code))
            }
            Expression::UnaryOp { op, expr } => {
                let expr_code = self.generate_expression(expr)?;
                let op_str = self.unaryop_to_rust(op);
                Ok(format!("({}{})", op_str, expr_code))
            }
            Expression::Index { base, index } => {
                let base_code = self.generate_expression(base)?;
                let index_code = self.generate_expression(index)?;
                // Bit extraction: (base >> index) & 1
                Ok(format!("(({} >> {}) & 1)", base_code, index_code))
            }
            Expression::Slice { base, high, low } => {
                let base_code = self.generate_expression(base)?;
                let width = high - low + 1;
                let mask = (1u64 << width) - 1;
                Ok(format!("(({} >> {}) & 0x{:x})", base_code, low, mask))
            }
            Expression::MethodCall { receiver, method, args: _ } => {
                let recv_code = self.generate_expression(receiver)?;
                match method.as_str() {
                    "posedge" | "negedge" => Ok(format!("{}.{}()", recv_code, method)),
                    _ => Ok(recv_code),
                }
            }
            Expression::If { condition, then_expr, else_expr } => {
                let cond_code = self.generate_expression(condition)?;
                let then_code = self.generate_expression(then_expr)?;
                let else_code = self.generate_expression(else_expr)?;
                Ok(format!("if {} != 0 {{ {} }} else {{ {} }}", cond_code, then_code, else_code))
            }
            Expression::Concat(exprs) => {
                // Concatenation: shift and or
                let mut result = String::new();
                let mut shift = 0;
                for (i, e) in exprs.iter().rev().enumerate() {
                    let e_code = self.generate_expression(e)?;
                    if i == 0 {
                        result = e_code;
                    } else {
                        shift += 8; // Simplified: assume 8-bit elements
                        result = format!("(({} << {}) | ({}))", e_code, shift, result);
                    }
                }
                Ok(result)
            }
            Expression::MemRead { mem_name, addr } => {
                // Memory read is not yet supported in compiled simulation
                let _ = (mem_name, addr);
                Err(CodeGenError::UnsupportedFeature("memory read".to_string()))
            }
        }
    }

    /// Generate literal code
    fn generate_literal(&self, lit: &Literal) -> Result<String, CodeGenError> {
        match lit {
            Literal::Binary { value, .. } => Ok(format!("0b{:b}", value)),
            Literal::Hex { value, .. } => Ok(format!("0x{:x}", value)),
            Literal::Decimal { value, .. } => Ok(format!("{}", value)),
        }
    }

    /// Convert binary operator to Rust
    fn binop_to_rust(&self, op: &BinOp) -> &'static str {
        match op {
            BinOp::Add => "+",
            BinOp::Sub => "-",
            BinOp::Mul => "*",
            BinOp::Div => "/",
            BinOp::Mod => "%",
            BinOp::And => "&",
            BinOp::Or => "|",
            BinOp::Xor => "^",
            BinOp::Shl => "<<",
            BinOp::Shr => ">>",
            BinOp::Eq => "==",
            BinOp::Ne => "!=",
            BinOp::Lt => "<",
            BinOp::Le => "<=",
            BinOp::Gt => ">",
            BinOp::Ge => ">=",
            BinOp::LogicalAnd => "&&",
            BinOp::LogicalOr => "||",
        }
    }

    /// Convert unary operator to Rust
    fn unaryop_to_rust(&self, op: &UnaryOp) -> &'static str {
        match op {
            UnaryOp::Not => "!",
            UnaryOp::Neg => "-",
            UnaryOp::LogNot => "!",
        }
    }

    /// Generate value recording code
    fn generate_value_recording(&mut self, module: &Module) -> Result<(), CodeGenError> {
        self.writeln("// Record signal values");
        self.writeln("tracer.record(\"clk\", clk.get_time(), clk.as_u64());");
        self.writeln("tracer.record(\"rst\", clk.get_time(), rst.as_u64());");

        for port in &module.ports {
            if matches!(port.ty, Type::Clock | Type::Reset { .. }) {
                continue;
            }
            self.writeln(&format!(
                "tracer.record(\"{}\", clk.get_time(), {} as u64);",
                port.name, port.name
            ));
        }

        for signal in &module.signals {
            self.writeln(&format!(
                "tracer.record(\"{}\", clk.get_time(), {} as u64);",
                signal.name, signal.name
            ));
        }

        Ok(())
    }

    /// Generate waveform output code
    fn generate_waveform_output(&mut self, _module: &Module) -> Result<(), CodeGenError> {
        self.writeln("// Write waveform");
        self.writeln("tracer.write_vcd(output_path).expect(\"Failed to write VCD\");");
        Ok(())
    }

    /// Generate a standalone Cargo.toml for the compiled simulation
    pub fn generate_cargo_toml(&self, module_name: &str, runtime_path: &str) -> String {
        format!(
            r#"[package]
name = "{}-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
iris-runtime = {{ path = "{}" }}
"#,
            module_name.to_lowercase(),
            runtime_path
        )
    }
}

impl Default for RustCodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

/// Code generator for test modules with DUT instantiation
pub struct TestCodeGenerator {
    output: String,
    indent: usize,
    /// All modules in the project (DUTs)
    dut_modules: HashMap<String, Module>,
    /// The test module
    test_module: Option<Module>,
    /// Signals from test module
    signals: Vec<(String, usize)>,
    /// Instance names and their module types
    instances: Vec<(String, String)>,
}

impl TestCodeGenerator {
    /// Create a new test code generator
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            dut_modules: HashMap::new(),
            test_module: None,
            signals: Vec::new(),
            instances: Vec::new(),
        }
    }

    /// Generate Rust code from a project with test module
    pub fn generate(&mut self, project: &Project) -> Result<String, CodeGenError> {
        self.output.clear();
        self.signals.clear();
        self.instances.clear();
        self.indent = 0;

        // Find test module and DUT modules
        let mut test_module: Option<Module> = None;
        self.dut_modules.clear();

        for (name, module) in project.get_all_modules() {
            if module.is_test {
                if test_module.is_some() {
                    return Err(CodeGenError::UnsupportedFeature(
                        "Multiple test modules not supported".to_string(),
                    ));
                }
                test_module = Some(module.clone());
            } else {
                self.dut_modules.insert(name.clone(), module.clone());
            }
        }

        let test_mod = test_module.ok_or_else(|| {
            CodeGenError::UnsupportedFeature("No test module found".to_string())
        })?;
        self.test_module = Some(test_mod.clone());

        // Collect signals from test module
        self.collect_test_signals(&test_mod);

        // Collect instances
        for inst in &test_mod.instances {
            self.instances.push((inst.name.clone(), inst.module_name.clone()));
        }

        // Generate header
        self.generate_header(&test_mod);

        // Generate DUT structures
        // Clone the DUT modules to avoid borrow issues
        let duts_to_generate: Vec<_> = test_mod.instances
            .iter()
            .filter_map(|inst| {
                self.dut_modules.get(&inst.module_name).cloned()
            })
            .collect();

        for dut in &duts_to_generate {
            self.generate_dut_struct(dut)?;
        }

        // Generate main function
        self.generate_test_main(&test_mod)?;

        Ok(self.output.clone())
    }

    /// Collect signals from test module
    fn collect_test_signals(&mut self, module: &Module) {
        for signal in &module.signals {
            let width = self.type_to_width(&signal.ty);
            self.signals.push((signal.name.clone(), width));
        }
    }

    /// Get bit width from type
    fn type_to_width(&self, ty: &Type) -> usize {
        match ty {
            Type::Bit => 1,
            Type::BitVec { width } => *width,
            Type::Clock => 1,
            Type::Reset { .. } => 1,
            Type::Array { element, size } => self.type_to_width(element) * size,
            Type::Named(_) => 32,
        }
    }

    /// Get Rust type for IRIS type
    fn type_to_rust(&self, ty: &Type) -> String {
        match ty {
            Type::Bit => "u8".to_string(),
            Type::BitVec { width } => {
                if *width <= 8 {
                    "u8".to_string()
                } else if *width <= 16 {
                    "u16".to_string()
                } else if *width <= 32 {
                    "u32".to_string()
                } else {
                    "u64".to_string()
                }
            }
            Type::Clock => "bool".to_string(),
            Type::Reset { .. } => "bool".to_string(),
            Type::Array { element, size } => {
                format!("[{}; {}]", self.type_to_rust(element), size)
            }
            Type::Named(_) => "u32".to_string(),
        }
    }

    /// Get bit mask for width
    fn width_to_mask(&self, width: usize) -> String {
        if width >= 64 {
            "u64::MAX".to_string()
        } else {
            format!("0x{:x}", (1u64 << width) - 1)
        }
    }

    /// Write a line with indentation
    fn writeln(&mut self, line: &str) {
        let indent_str = "    ".repeat(self.indent);
        self.output.push_str(&indent_str);
        self.output.push_str(line);
        self.output.push('\n');
    }

    /// Generate file header
    fn generate_header(&mut self, module: &Module) {
        self.writeln("//! Auto-generated IRIS test simulation code");
        self.writeln(&format!("//! Test: {}", module.name));
        self.writeln("//!");
        self.writeln("//! This file was generated by iris-compile.");
        self.writeln("//! Do not edit manually.");
        self.writeln("");
        self.writeln("use iris_runtime::{Clock, Reset, WaveTracer};");
        self.writeln("use std::env;");
        self.writeln("");
    }

    /// Generate DUT structure
    fn generate_dut_struct(&mut self, module: &Module) -> Result<(), CodeGenError> {
        self.writeln(&format!("/// DUT: {} module", module.name));
        self.writeln("#[derive(Default)]");
        self.writeln(&format!("struct {} {{", module.name));
        self.indent += 1;

        // Input ports (excluding clock/reset)
        for port in &module.ports {
            if matches!(port.ty, Type::Clock | Type::Reset { .. }) {
                continue;
            }
            let rust_type = self.type_to_rust(&port.ty);
            self.writeln(&format!("{}: {},", port.name, rust_type));
        }

        // Internal signals
        for signal in &module.signals {
            let rust_type = self.type_to_rust(&signal.ty);
            self.writeln(&format!("{}: {},", signal.name, rust_type));
        }

        self.indent -= 1;
        self.writeln("}");
        self.writeln("");

        // Generate impl block
        self.writeln(&format!("impl {} {{", module.name));
        self.indent += 1;

        // new() method
        self.writeln("fn new() -> Self {");
        self.indent += 1;
        self.writeln("Self::default()");
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");

        // reset() method
        self.writeln("fn reset(&mut self) {");
        self.indent += 1;
        for signal in &module.signals {
            self.writeln(&format!("self.{} = 0;", signal.name));
        }
        for port in &module.ports {
            if matches!(port.direction, PortDirection::Out) {
                if !matches!(port.ty, Type::Clock | Type::Reset { .. }) {
                    self.writeln(&format!("self.{} = 0;", port.name));
                }
            }
        }
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");

        // posedge() method - sequential logic
        self.writeln("fn posedge(&mut self, rst_active: bool) {");
        self.indent += 1;
        self.writeln("if rst_active {");
        self.indent += 1;
        self.writeln("self.reset();");
        self.writeln("return;");
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");

        // Generate sync block logic
        for block in &module.logic_blocks {
            if let LogicBlock::Sync(sync) = block {
                self.generate_dut_sync_statements(&sync.statements)?;
            }
        }

        self.indent -= 1;
        self.writeln("}");
        self.writeln("");

        // comb() method - combinational logic
        self.writeln("fn comb(&mut self) {");
        self.indent += 1;
        for block in &module.logic_blocks {
            if let LogicBlock::Comb(comb) = block {
                self.generate_dut_comb_statements(&comb.statements)?;
            }
        }
        self.indent -= 1;
        self.writeln("}");

        self.indent -= 1;
        self.writeln("}");
        self.writeln("");

        Ok(())
    }

    /// Generate DUT sync block statements
    fn generate_dut_sync_statements(&mut self, stmts: &[Statement]) -> Result<(), CodeGenError> {
        for stmt in stmts {
            self.generate_dut_statement(stmt, true)?;
        }
        Ok(())
    }

    /// Generate DUT comb block statements
    fn generate_dut_comb_statements(&mut self, stmts: &[Statement]) -> Result<(), CodeGenError> {
        for stmt in stmts {
            self.generate_dut_statement(stmt, true)?;
        }
        Ok(())
    }

    /// Generate a statement for DUT (with self. prefix)
    fn generate_dut_statement(&mut self, stmt: &Statement, use_self: bool) -> Result<(), CodeGenError> {
        match stmt {
            Statement::Assign { target, value } => {
                let value_code = self.generate_expression(value, use_self)?;
                let prefix = if use_self { "self." } else { "" };
                self.writeln(&format!("{}{} = {};", prefix, target, value_code));
            }
            Statement::If {
                condition,
                then_branch,
                else_branch,
            } => {
                let cond_code = self.generate_expression(condition, use_self)?;
                self.writeln(&format!("if {} != 0 {{", cond_code));
                self.indent += 1;
                for s in then_branch {
                    self.generate_dut_statement(s, use_self)?;
                }
                self.indent -= 1;
                if let Some(else_stmts) = else_branch {
                    self.writeln("} else {");
                    self.indent += 1;
                    for s in else_stmts {
                        self.generate_dut_statement(s, use_self)?;
                    }
                    self.indent -= 1;
                }
                self.writeln("}");
            }
            Statement::Match { .. } => {
                return Err(CodeGenError::UnsupportedFeature("match statement".to_string()));
            }
            Statement::For { var, range, body } => {
                let start = self.generate_expression(&range.start, use_self)?;
                let end = self.generate_expression(&range.end, use_self)?;
                let range_op = if range.inclusive { "..=" } else { ".." };
                self.writeln(&format!("for {} in {}{}{} {{", var, start, range_op, end));
                self.indent += 1;
                for s in body {
                    self.generate_dut_statement(s, use_self)?;
                }
                self.indent -= 1;
                self.writeln("}");
            }
            Statement::While { condition, body } => {
                let cond_code = self.generate_expression(condition, use_self)?;
                self.writeln(&format!("while {} != 0 {{", cond_code));
                self.indent += 1;
                for s in body {
                    self.generate_dut_statement(s, use_self)?;
                }
                self.indent -= 1;
                self.writeln("}");
            }
        }
        Ok(())
    }

    /// Generate main function for test
    fn generate_test_main(&mut self, test_mod: &Module) -> Result<(), CodeGenError> {
        self.writeln("fn main() {");
        self.indent += 1;

        // Parse command line arguments
        self.writeln("let args: Vec<String> = env::args().collect();");
        self.writeln("let cycles: u64 = args.get(1)");
        self.indent += 1;
        self.writeln(".and_then(|s| s.parse().ok())");
        self.writeln(".unwrap_or(100);");
        self.indent -= 1;
        self.writeln("let output_path = args.get(2)");
        self.indent += 1;
        self.writeln(".map(|s| s.as_str())");
        self.writeln(&format!(".unwrap_or(\"{}.vcd\");", test_mod.name.to_lowercase()));
        self.indent -= 1;
        self.writeln("");

        // Clock and reset
        self.writeln("// Clock and reset");
        self.writeln("let mut clk = Clock::new(10_000); // 10ns period");
        self.writeln("let mut rst = Reset::new();");
        self.writeln("");

        // Test signals
        self.writeln("// Test signals");
        for signal in &test_mod.signals {
            if matches!(signal.ty, Type::Clock | Type::Reset { .. }) {
                continue;
            }
            let rust_type = self.type_to_rust(&signal.ty);
            let init = if let Some(ref expr) = signal.init_value {
                self.generate_expression(expr, false)?
            } else {
                "0".to_string()
            };
            self.writeln(&format!("let mut {}: {} = {};", signal.name, rust_type, init));
        }
        self.writeln("");

        // DUT instances
        self.writeln("// DUT instances");
        for inst in &test_mod.instances {
            self.writeln(&format!("let mut {} = {}::new();", inst.name, inst.module_name));
        }
        self.writeln("");

        // Wave tracer setup
        self.generate_test_tracer_setup(test_mod)?;

        // Reset sequence
        self.generate_test_reset_sequence(test_mod)?;

        // Main simulation loop
        self.generate_test_simulation_loop(test_mod)?;

        // Waveform output
        self.generate_test_waveform_output()?;

        // Summary output
        self.generate_test_summary(test_mod)?;

        self.indent -= 1;
        self.writeln("}");

        Ok(())
    }

    /// Generate wave tracer setup
    fn generate_test_tracer_setup(&mut self, test_mod: &Module) -> Result<(), CodeGenError> {
        self.writeln("// Wave tracer setup");
        self.writeln("let mut tracer = WaveTracer::new();");
        self.writeln("tracer.register(\"clk\", 1);");
        self.writeln("tracer.register(\"rst\", 1);");

        // Test signals
        for signal in &test_mod.signals {
            if matches!(signal.ty, Type::Clock | Type::Reset { .. }) {
                continue;
            }
            let width = self.type_to_width(&signal.ty);
            self.writeln(&format!("tracer.register(\"{}\", {});", signal.name, width));
        }

        // Collect DUT signal info first (to avoid borrow issues)
        let mut dut_signals: Vec<(String, String, usize)> = Vec::new();
        for inst in &test_mod.instances {
            if let Some(dut) = self.dut_modules.get(&inst.module_name) {
                for signal in &dut.signals {
                    let width = self.type_to_width(&signal.ty);
                    dut_signals.push((inst.name.clone(), signal.name.clone(), width));
                }
                for port in &dut.ports {
                    if matches!(port.ty, Type::Clock | Type::Reset { .. }) {
                        continue;
                    }
                    let width = self.type_to_width(&port.ty);
                    dut_signals.push((inst.name.clone(), port.name.clone(), width));
                }
            }
        }

        // Write DUT signal registrations
        for (inst_name, sig_name, width) in dut_signals {
            self.writeln(&format!(
                "tracer.register(\"{}.{}\", {});",
                inst_name, sig_name, width
            ));
        }

        self.writeln("");
        Ok(())
    }

    /// Generate reset sequence
    fn generate_test_reset_sequence(&mut self, test_mod: &Module) -> Result<(), CodeGenError> {
        self.writeln("// Reset sequence");
        self.writeln("rst.assert();");
        self.writeln("for _ in 0..4 {  // Even number of ticks to end with clock low");
        self.indent += 1;
        self.writeln("clk.tick();");

        // Reset DUT instances
        for inst in &test_mod.instances {
            self.writeln(&format!("{}.reset();", inst.name));
        }

        self.writeln("tracer.record(\"clk\", clk.get_time(), clk.as_u64());");
        self.writeln("tracer.record(\"rst\", clk.get_time(), rst.as_u64());");
        self.indent -= 1;
        self.writeln("}");
        self.writeln("rst.deassert();");
        self.writeln("");
        Ok(())
    }

    /// Generate main simulation loop
    fn generate_test_simulation_loop(&mut self, test_mod: &Module) -> Result<(), CodeGenError> {
        self.writeln("// Main simulation loop");
        self.writeln("for _cycle in 0..cycles {");
        self.indent += 1;

        self.writeln("clk.tick(); // Rising edge");
        self.writeln("");

        // Posedge evaluation
        self.writeln("if clk.posedge() {");
        self.indent += 1;

        // Update DUT input ports from test signals
        self.writeln("// Update DUT inputs");
        for inst in &test_mod.instances {
            for (port_name, expr) in &inst.port_connections {
                if let Some(dut) = self.dut_modules.get(&inst.module_name) {
                    // Check if port is input
                    if let Some(port) = dut.ports.iter().find(|p| &p.name == port_name) {
                        if matches!(port.direction, PortDirection::In) {
                            if !matches!(port.ty, Type::Clock | Type::Reset { .. }) {
                                let expr_code = self.generate_expression(expr, false)?;
                                self.writeln(&format!("{}.{} = {};", inst.name, port_name, expr_code));
                            }
                        }
                    }
                }
            }
        }
        self.writeln("");

        // DUT posedge
        self.writeln("// DUT sequential logic");
        for inst in &test_mod.instances {
            self.writeln(&format!("{}.posedge(rst.is_active());", inst.name));
        }
        self.writeln("");

        // Test sync block
        self.writeln("// Test sequential logic");
        self.writeln("if !rst.is_active() {");
        self.indent += 1;
        for block in &test_mod.logic_blocks {
            if let LogicBlock::Sync(sync) = block {
                for stmt in &sync.statements {
                    self.generate_test_statement(stmt, test_mod)?;
                }
            }
        }
        self.indent -= 1;
        self.writeln("}");

        self.indent -= 1;
        self.writeln("}");
        self.writeln("");

        // DUT combinational logic
        self.writeln("// DUT combinational logic");
        for inst in &test_mod.instances {
            self.writeln(&format!("{}.comb();", inst.name));
        }
        self.writeln("");

        // Test combinational logic
        self.writeln("// Test combinational logic");
        for block in &test_mod.logic_blocks {
            if let LogicBlock::Comb(comb) = block {
                for stmt in &comb.statements {
                    self.generate_test_statement(stmt, test_mod)?;
                }
            }
        }
        self.writeln("");

        // Record values
        self.generate_test_value_recording(test_mod)?;

        self.writeln("clk.tick(); // Falling edge");

        self.indent -= 1;
        self.writeln("}");
        self.writeln("");

        Ok(())
    }

    /// Generate a statement for test module
    fn generate_test_statement(&mut self, stmt: &Statement, test_mod: &Module) -> Result<(), CodeGenError> {
        match stmt {
            Statement::Assign { target, value } => {
                let value_code = self.generate_test_expression(value, test_mod)?;

                // Find signal width for masking
                if let Some((_, width)) = self.signals.iter().find(|(n, _)| n == target) {
                    if *width < 64 {
                        let mask = self.width_to_mask(*width);
                        self.writeln(&format!("{} = ({}) & {};", target, value_code, mask));
                    } else {
                        self.writeln(&format!("{} = {};", target, value_code));
                    }
                } else {
                    self.writeln(&format!("{} = {};", target, value_code));
                }
            }
            Statement::If {
                condition,
                then_branch,
                else_branch,
            } => {
                let cond_code = self.generate_test_expression(condition, test_mod)?;
                // Check if condition is already a boolean expression
                let cond_str = if self.is_boolean_expression(condition) {
                    cond_code
                } else {
                    format!("{} != 0", cond_code)
                };
                self.writeln(&format!("if {} {{", cond_str));
                self.indent += 1;
                for s in then_branch {
                    self.generate_test_statement(s, test_mod)?;
                }
                self.indent -= 1;
                if let Some(else_stmts) = else_branch {
                    self.writeln("} else {");
                    self.indent += 1;
                    for s in else_stmts {
                        self.generate_test_statement(s, test_mod)?;
                    }
                    self.indent -= 1;
                }
                self.writeln("}");
            }
            Statement::Match { .. } => {
                return Err(CodeGenError::UnsupportedFeature("match statement".to_string()));
            }
            Statement::For { var, range, body } => {
                let start = self.generate_test_expression(&range.start, test_mod)?;
                let end = self.generate_test_expression(&range.end, test_mod)?;
                let range_op = if range.inclusive { "..=" } else { ".." };
                self.writeln(&format!("for {} in {}{}{} {{", var, start, range_op, end));
                self.indent += 1;
                for s in body {
                    self.generate_test_statement(s, test_mod)?;
                }
                self.indent -= 1;
                self.writeln("}");
            }
            Statement::While { condition, body } => {
                let cond_code = self.generate_test_expression(condition, test_mod)?;
                self.writeln(&format!("while {} != 0 {{", cond_code));
                self.indent += 1;
                for s in body {
                    self.generate_test_statement(s, test_mod)?;
                }
                self.indent -= 1;
                self.writeln("}");
            }
        }
        Ok(())
    }

    /// Generate expression for test module (handles hierarchical references)
    fn generate_test_expression(&self, expr: &Expression, test_mod: &Module) -> Result<String, CodeGenError> {
        match expr {
            Expression::Literal(lit) => self.generate_literal(lit),
            Expression::Ident(name) => {
                // Check if it's a hierarchical reference like "dut.count"
                if name.contains('.') {
                    Ok(name.replace('.', "."))
                } else {
                    Ok(name.clone())
                }
            }
            Expression::BinOp { op, lhs, rhs } => {
                let lhs_code = self.generate_test_expression(lhs, test_mod)?;
                let rhs_code = self.generate_test_expression(rhs, test_mod)?;
                let op_str = self.binop_to_rust(op);
                Ok(format!("({} {} {})", lhs_code, op_str, rhs_code))
            }
            Expression::UnaryOp { op, expr } => {
                let expr_code = self.generate_test_expression(expr, test_mod)?;
                let op_str = self.unaryop_to_rust(op);
                Ok(format!("({}{})", op_str, expr_code))
            }
            Expression::Index { base, index } => {
                let base_code = self.generate_test_expression(base, test_mod)?;
                let index_code = self.generate_test_expression(index, test_mod)?;
                Ok(format!("(({} >> {}) & 1)", base_code, index_code))
            }
            Expression::Slice { base, high, low } => {
                let base_code = self.generate_test_expression(base, test_mod)?;
                let width = high - low + 1;
                let mask = (1u64 << width) - 1;
                Ok(format!("(({} >> {}) & 0x{:x})", base_code, low, mask))
            }
            Expression::MethodCall { receiver, method, args: _ } => {
                let recv_code = self.generate_test_expression(receiver, test_mod)?;
                match method.as_str() {
                    "posedge" | "negedge" => Ok(format!("{}.{}()", recv_code, method)),
                    // Hierarchical signal access (e.g., dut.count)
                    _ => Ok(format!("{}.{}", recv_code, method)),
                }
            }
            Expression::If { condition, then_expr, else_expr } => {
                let cond_code = self.generate_test_expression(condition, test_mod)?;
                let then_code = self.generate_test_expression(then_expr, test_mod)?;
                let else_code = self.generate_test_expression(else_expr, test_mod)?;
                // Check if condition is already a boolean expression
                let cond_str = if self.is_boolean_expression(condition) {
                    cond_code
                } else {
                    format!("{} != 0", cond_code)
                };
                Ok(format!("if {} {{ {} }} else {{ {} }}", cond_str, then_code, else_code))
            }
            Expression::Concat(exprs) => {
                let mut result = String::new();
                let mut shift = 0;
                for (i, e) in exprs.iter().rev().enumerate() {
                    let e_code = self.generate_test_expression(e, test_mod)?;
                    if i == 0 {
                        result = e_code;
                    } else {
                        shift += 8;
                        result = format!("(({} << {}) | ({}))", e_code, shift, result);
                    }
                }
                Ok(result)
            }
            Expression::MemRead { mem_name, addr } => {
                let _ = (mem_name, addr);
                Err(CodeGenError::UnsupportedFeature("memory read".to_string()))
            }
        }
    }

    /// Generate expression (for DUT, with optional self prefix)
    fn generate_expression(&self, expr: &Expression, use_self: bool) -> Result<String, CodeGenError> {
        match expr {
            Expression::Literal(lit) => self.generate_literal(lit),
            Expression::Ident(name) => {
                if use_self {
                    Ok(format!("self.{}", name))
                } else {
                    Ok(name.clone())
                }
            }
            Expression::BinOp { op, lhs, rhs } => {
                let lhs_code = self.generate_expression(lhs, use_self)?;
                let rhs_code = self.generate_expression(rhs, use_self)?;
                let op_str = self.binop_to_rust(op);
                Ok(format!("({} {} {})", lhs_code, op_str, rhs_code))
            }
            Expression::UnaryOp { op, expr } => {
                let expr_code = self.generate_expression(expr, use_self)?;
                let op_str = self.unaryop_to_rust(op);
                Ok(format!("({}{})", op_str, expr_code))
            }
            Expression::Index { base, index } => {
                let base_code = self.generate_expression(base, use_self)?;
                let index_code = self.generate_expression(index, use_self)?;
                Ok(format!("(({} >> {}) & 1)", base_code, index_code))
            }
            Expression::Slice { base, high, low } => {
                let base_code = self.generate_expression(base, use_self)?;
                let width = high - low + 1;
                let mask = (1u64 << width) - 1;
                Ok(format!("(({} >> {}) & 0x{:x})", base_code, low, mask))
            }
            Expression::MethodCall { receiver, method, args: _ } => {
                let recv_code = self.generate_expression(receiver, use_self)?;
                match method.as_str() {
                    "posedge" | "negedge" => Ok(format!("{}.{}()", recv_code, method)),
                    _ => Ok(recv_code),
                }
            }
            Expression::If { condition, then_expr, else_expr } => {
                let cond_code = self.generate_expression(condition, use_self)?;
                let then_code = self.generate_expression(then_expr, use_self)?;
                let else_code = self.generate_expression(else_expr, use_self)?;
                Ok(format!("if {} != 0 {{ {} }} else {{ {} }}", cond_code, then_code, else_code))
            }
            Expression::Concat(exprs) => {
                let mut result = String::new();
                let mut shift = 0;
                for (i, e) in exprs.iter().rev().enumerate() {
                    let e_code = self.generate_expression(e, use_self)?;
                    if i == 0 {
                        result = e_code;
                    } else {
                        shift += 8;
                        result = format!("(({} << {}) | ({}))", e_code, shift, result);
                    }
                }
                Ok(result)
            }
            Expression::MemRead { mem_name, addr } => {
                let _ = (mem_name, addr);
                Err(CodeGenError::UnsupportedFeature("memory read".to_string()))
            }
        }
    }

    /// Generate literal code
    fn generate_literal(&self, lit: &Literal) -> Result<String, CodeGenError> {
        match lit {
            Literal::Binary { value, .. } => Ok(format!("0b{:b}", value)),
            Literal::Hex { value, .. } => Ok(format!("0x{:x}", value)),
            Literal::Decimal { value, .. } => Ok(format!("{}", value)),
        }
    }

    /// Convert binary operator to Rust
    fn binop_to_rust(&self, op: &BinOp) -> &'static str {
        match op {
            BinOp::Add => "+",
            BinOp::Sub => "-",
            BinOp::Mul => "*",
            BinOp::Div => "/",
            BinOp::Mod => "%",
            BinOp::And => "&",
            BinOp::Or => "|",
            BinOp::Xor => "^",
            BinOp::Shl => "<<",
            BinOp::Shr => ">>",
            BinOp::Eq => "==",
            BinOp::Ne => "!=",
            BinOp::Lt => "<",
            BinOp::Le => "<=",
            BinOp::Gt => ">",
            BinOp::Ge => ">=",
            BinOp::LogicalAnd => "&&",
            BinOp::LogicalOr => "||",
        }
    }

    /// Convert unary operator to Rust
    fn unaryop_to_rust(&self, op: &UnaryOp) -> &'static str {
        match op {
            UnaryOp::Not => "!",
            UnaryOp::Neg => "-",
            UnaryOp::LogNot => "!",
        }
    }

    /// Check if an expression returns a boolean value
    fn is_boolean_expression(&self, expr: &Expression) -> bool {
        match expr {
            Expression::BinOp { op, .. } => {
                matches!(
                    op,
                    BinOp::Eq | BinOp::Ne | BinOp::Lt | BinOp::Le | BinOp::Gt | BinOp::Ge |
                    BinOp::LogicalAnd | BinOp::LogicalOr
                )
            }
            Expression::UnaryOp { op: UnaryOp::LogNot, .. } => true,
            _ => false,
        }
    }

    /// Generate value recording code
    fn generate_test_value_recording(&mut self, test_mod: &Module) -> Result<(), CodeGenError> {
        self.writeln("// Record signal values");
        self.writeln("tracer.record(\"clk\", clk.get_time(), clk.as_u64());");
        self.writeln("tracer.record(\"rst\", clk.get_time(), rst.as_u64());");

        // Test signals
        for signal in &test_mod.signals {
            if matches!(signal.ty, Type::Clock | Type::Reset { .. }) {
                continue;
            }
            self.writeln(&format!(
                "tracer.record(\"{}\", clk.get_time(), {} as u64);",
                signal.name, signal.name
            ));
        }

        // Collect DUT signal info first (to avoid borrow issues)
        let mut dut_signals: Vec<(String, String, bool)> = Vec::new(); // (inst_name, sig_name, is_clk_rst)
        for inst in &test_mod.instances {
            if let Some(dut) = self.dut_modules.get(&inst.module_name) {
                for signal in &dut.signals {
                    dut_signals.push((inst.name.clone(), signal.name.clone(), false));
                }
                for port in &dut.ports {
                    let skip = matches!(port.ty, Type::Clock | Type::Reset { .. });
                    if !skip {
                        dut_signals.push((inst.name.clone(), port.name.clone(), false));
                    }
                }
            }
        }

        // Write DUT signal recordings
        for (inst_name, sig_name, _) in dut_signals {
            self.writeln(&format!(
                "tracer.record(\"{}.{}\", clk.get_time(), {}.{} as u64);",
                inst_name, sig_name, inst_name, sig_name
            ));
        }

        Ok(())
    }

    /// Generate waveform output code
    fn generate_test_waveform_output(&mut self) -> Result<(), CodeGenError> {
        self.writeln("// Write waveform");
        self.writeln("tracer.write_vcd(output_path).expect(\"Failed to write VCD\");");
        Ok(())
    }

    /// Generate summary output
    fn generate_test_summary(&mut self, test_mod: &Module) -> Result<(), CodeGenError> {
        self.writeln("");
        self.writeln("println!(\"Simulation completed: {} cycles\", cycles);");
        self.writeln("println!(\"Final values:\");");

        // Collect DUT signal names first (to avoid borrow issues)
        let mut dut_signals: Vec<(String, String)> = Vec::new();
        for inst in &test_mod.instances {
            if let Some(dut) = self.dut_modules.get(&inst.module_name) {
                for signal in &dut.signals {
                    dut_signals.push((inst.name.clone(), signal.name.clone()));
                }
            }
        }

        // Write DUT signal summaries
        for (inst_name, sig_name) in dut_signals {
            self.writeln(&format!(
                "println!(\"  {}.{}: {{}}\", {}.{});",
                inst_name, sig_name, inst_name, sig_name
            ));
        }

        // Test result signals
        for signal in &test_mod.signals {
            if signal.name.contains("test") || signal.name.contains("pass") || signal.name.contains("result") {
                self.writeln(&format!(
                    "println!(\"  {}: {{}}\", {});",
                    signal.name, signal.name
                ));
            }
        }

        Ok(())
    }

    /// Generate Cargo.toml for test simulation
    pub fn generate_cargo_toml(&self, test_name: &str, runtime_path: &str) -> String {
        format!(
            r#"[package]
name = "{}-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
iris-runtime = {{ path = "{}" }}
"#,
            test_name.to_lowercase(),
            runtime_path
        )
    }
}

impl Default for TestCodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::ast::{Port, PortDirection, Signal};

    #[test]
    fn test_codegen_basic() {
        let module = Module {
            name: "Counter".to_string(),
            generics: vec![],
            ports: vec![
                Port {
                    name: "clk".to_string(),
                    direction: PortDirection::In,
                    ty: Type::Clock,
                },
                Port {
                    name: "rst".to_string(),
                    direction: PortDirection::In,
                    ty: Type::Reset { active_low: false },
                },
                Port {
                    name: "enable".to_string(),
                    direction: PortDirection::In,
                    ty: Type::Bit,
                },
                Port {
                    name: "count".to_string(),
                    direction: PortDirection::Out,
                    ty: Type::BitVec { width: 8 },
                },
            ],
            signals: vec![Signal {
                name: "counter".to_string(),
                ty: Type::BitVec { width: 8 },
                init_value: Some(Expression::Literal(Literal::Decimal {
                    width: Some(8),
                    value: 0,
                })),
                is_mutable: true,
                is_var: true,
            }],
            logic_blocks: vec![],
            instances: vec![],
            span: None,
            is_test: false,
            seq_blocks: vec![],
            initial_blocks: vec![],
            fsm_blocks: vec![],
            memories: vec![],
        };

        let mut gen = RustCodeGenerator::new();
        let result = gen.generate(&module);
        assert!(result.is_ok());
        let code = result.unwrap();
        assert!(code.contains("fn main()"));
        assert!(code.contains("Clock::new"));
        assert!(code.contains("WaveTracer::new"));
    }
}
