//! iris2sv: convert IRIS source to SystemVerilog.
//!
//! The Rust port of the TypeScript iris2sv (stage A4). It reads with
//! `iris-sim`'s parser — the same front end the simulator uses — and writes
//! SystemVerilog. A construct it cannot yet convert is refused with a message,
//! never silently dropped.

pub mod convert;

/// Convert IRIS source (one or more modules) to SystemVerilog text.
pub fn transpile(source: &str) -> Result<String, String> {
    let parser = iris_sim::parser::Parser::new();
    let parsed = parser.parse_all(source).map_err(|e| e.to_string())?;
    let mut out = String::new();
    out.push_str("// Generated by iris2sv\n// Do not edit manually\n\n");
    // File-level declarations come first, each followed by three blank lines,
    // matching the TypeScript tool.
    // typedefs (enum/struct) are followed by three blank lines; functions and
    // interfaces by two, matching the TypeScript tool.
    for e in &parsed.enums {
        out.push_str(&convert::enum_decl_to_sv(e));
        out.push_str("\n\n\n\n");
    }
    for s in &parsed.structs {
        out.push_str(&convert::struct_decl_to_sv(s)?);
        out.push_str("\n\n\n\n");
    }
    for i in &parsed.interfaces {
        out.push_str(&convert::interface_decl_to_sv(i)?);
        out.push_str("\n\n\n");
    }
    for f in &parsed.functions {
        out.push_str(&convert::function_decl_to_sv(f)?);
        out.push_str("\n\n\n");
    }
    // Modules in this file are known to each other, so an instance of one can
    // have its output ports wired.
    let mut modules = std::collections::HashMap::new();
    for m in &parsed.modules {
        modules.insert(m.name.clone(), m.clone());
    }
    // Each module is followed by a blank line, so modules are separated and the
    // file ends with one.
    for module in &parsed.modules {
        out.push_str(&convert::module_to_sv(module, &modules)?);
        out.push('\n');
    }
    Ok(out)
}
