// Generated by iris2sv
// Do not edit manually

module AsyncFifo #(
  parameter logic [31:0] DataWidth = 8,
  parameter logic [31:0] Depth = 16,
  parameter logic [31:0] AddrWidth = $clog2(Depth),
  parameter logic [31:0] PtrWidth = $clog2(Depth) + 1
) (
  input  logic                 wr_clk,
  input  logic                 wr_rst_n,
  input  logic                 wr_en,
  input  logic [DataWidth-1:0] wr_data,
  input  logic                 rd_clk,
  input  logic                 rd_rst_n,
  input  logic                 rd_en,
  output logic                 full,
  output logic                 empty,
  output logic [DataWidth-1:0] rd_data
);

// Internal signals
  logic [PtrWidth-1:0] wr_ptr = 0;
  logic [PtrWidth-1:0] wr_ptr_gray = 0;
  logic [PtrWidth-1:0] rd_ptr_gray_sync1 = 0;
  logic [PtrWidth-1:0] rd_ptr_gray_sync2 = 0;
  logic [PtrWidth-1:0] rd_ptr = 0;
  logic [PtrWidth-1:0] rd_ptr_gray = 0;
  logic [PtrWidth-1:0] wr_ptr_gray_sync1 = 0;
  logic [PtrWidth-1:0] wr_ptr_gray_sync2 = 0;
  logic [DataWidth-1:0] storage [Depth];

  always_comb begin
    rd_data = storage[rd_ptr[32'(AddrWidth - 1):0]];
    empty = rd_ptr_gray == wr_ptr_gray_sync2;
    full = wr_ptr_gray == {~rd_ptr_gray_sync2[32'(PtrWidth - 1):32'(PtrWidth - 2)], rd_ptr_gray_sync2[32'(PtrWidth - 3):0]};
  end

  always_ff @(posedge wr_clk or negedge wr_rst_n) 
    if (~wr_rst_n) begin
      wr_ptr <= 0;
      wr_ptr_gray <= 0;
      rd_ptr_gray_sync1 <= 0;
      rd_ptr_gray_sync2 <= 0;
    end
    else begin
      rd_ptr_gray_sync1 <= rd_ptr_gray;
      rd_ptr_gray_sync2 <= rd_ptr_gray_sync1;
      if (wr_en) 
        if (~full) begin
          storage[wr_ptr[32'(AddrWidth - 1):0]] <= wr_data;
          wr_ptr <= PtrWidth'(wr_ptr + 1);
          wr_ptr_gray <= PtrWidth'(wr_ptr + 1) ^ PtrWidth'(wr_ptr + 1) >> 1;
        end
    end

  always_ff @(posedge rd_clk or negedge rd_rst_n) 
    if (~rd_rst_n) begin
      rd_ptr <= 0;
      rd_ptr_gray <= 0;
      wr_ptr_gray_sync1 <= 0;
      wr_ptr_gray_sync2 <= 0;
    end
    else begin
      wr_ptr_gray_sync1 <= wr_ptr_gray;
      wr_ptr_gray_sync2 <= wr_ptr_gray_sync1;
      if (rd_en) 
        if (~empty) begin
          rd_ptr <= PtrWidth'(rd_ptr + 1);
          rd_ptr_gray <= PtrWidth'(rd_ptr + 1) ^ PtrWidth'(rd_ptr + 1) >> 1;
        end
    end

endmodule

