/**
 * Compiler E2E Tests
 *
 * Tests the full compilation pipeline from IRIS source to SystemVerilog.
 */

import { describe, it, expect } from 'vitest';
import { compile, createCompiler } from '../compiler.js';

describe('Compiler', () => {
  describe('compile()', () => {
    it('should compile empty module', () => {
      const source = `
mod empty() {}
`;
      const result = compile(source);

      expect(result.success).toBe(true);
      expect(result.parseErrors).toHaveLength(0);
      expect(result.output).toContain('module empty');
      expect(result.output).toContain('endmodule');
    });

    it('should compile module with input/output ports', () => {
      const source = `
mod passthrough(
  in data_in: bit[8],
  out data_out: bit[8]
) {}
`;
      const result = compile(source);

      expect(result.success).toBe(true);
      expect(result.output).toContain('module passthrough');
      expect(result.output).toContain('input  logic [7:0] data_in');
      expect(result.output).toContain('output logic [7:0] data_out');
    });

    it('should compile module with inout port', () => {
      const source = `
mod bidirectional(
  inout io: bit[4]
) {}
`;
      const result = compile(source);

      expect(result.success).toBe(true);
      expect(result.output).toContain('module bidirectional');
      expect(result.output).toContain('inout logic [3:0] io');
    });

    it('should compile module with boolean port', () => {
      const source = `
mod with_bool(
  in flag: bool,
  out result: bool
) {}
`;
      const result = compile(source);

      expect(result.success).toBe(true);
      expect(result.output).toContain('input  logic flag');
      expect(result.output).toContain('output logic result');
    });

    it('should report parse errors', () => {
      const source = `
mod broken(
  in missing_type:
) {}
`;
      const result = compile(source);

      expect(result.success).toBe(false);
      expect(result.parseErrors.length).toBeGreaterThan(0);
    });

    it('should generate header comments', () => {
      const source = `mod test() {}`;
      const result = compile(source);

      expect(result.success).toBe(true);
      expect(result.output).toContain('// Generated by iris2sv');
      expect(result.output).toContain('// Do not edit manually');
    });
  });

  describe('createCompiler()', () => {
    it('should respect verbose option', () => {
      const compiler = createCompiler({ verbose: true });
      const result = compiler.compile('mod test() {}');

      expect(result.success).toBe(true);
    });

    it('should respect checkOnly option', () => {
      const compiler = createCompiler({ checkOnly: true });
      const result = compiler.compile('mod test() {}');

      expect(result.success).toBe(true);
      expect(result.output).toBeNull();
    });

    it('should handle strict mode', () => {
      // Strict mode treats warnings as errors
      const compiler = createCompiler({ strict: true });
      const source = `
mod unused_port(
  in unused: bit[8]
) {}
`;
      const result = compiler.compile(source);

      // With strict mode, the unused port warning should cause failure
      // (depending on analyzer configuration)
      expect(result.diagnostics).toBeDefined();
    });
  });

  describe('Port width handling', () => {
    it('should handle 1-bit ports', () => {
      const source = `
mod single_bit(
  in a: bit,
  out b: bit
) {}
`;
      const result = compile(source);

      expect(result.success).toBe(true);
      expect(result.output).toContain('input  logic a');
      expect(result.output).toContain('output logic b');
    });

    it('should handle 16-bit ports', () => {
      const source = `
mod wide_port(
  in data: bit[16]
) {}
`;
      const result = compile(source);

      expect(result.success).toBe(true);
      expect(result.output).toContain('input logic [15:0] data');
    });

    it('should handle 32-bit ports', () => {
      const source = `
mod u32_port(
  in value: bit[32]
) {}
`;
      const result = compile(source);

      expect(result.success).toBe(true);
      expect(result.output).toContain('input logic [31:0] value');
    });
  });

  describe('Multiple modules', () => {
    it('should compile multiple modules in one file', () => {
      const source = `
mod module_a(in x: bit[8]) {}
mod module_b(out y: bit[8]) {}
`;
      const result = compile(source);

      expect(result.success).toBe(true);
      expect(result.output).toContain('module module_a');
      expect(result.output).toContain('module module_b');
    });
  });

  describe('Visibility', () => {
    it('should compile public module', () => {
      const source = `
pub mod public_mod(in a: bit) {}
`;
      const result = compile(source);

      expect(result.success).toBe(true);
      expect(result.output).toContain('module public_mod');
    });
  });
});
